on:
  push:
    branches:
       - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: aws credentials
      - name: copy files to s3
      - run: |
          tar -cvzf ./assessment/s3-helm.tgz ./assessment/s3-helm/
          aws s3 sync ./*.tgz s3://AWS_S3_BUCKET/charts/
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'   # optional: defaults to us-east-1
