name: Upload Website

on:
  push:
    branches:
    - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: 'us-east-1'
  aws-region: 'us-east-1'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
    - name: compress helm chart
      run: tar -cvzf ./assessment/s3-helm.tgz ./assessment/s3-helm/
    - name: Deploy static site to S3 bucket
      run: aws s3 sync ./assessment/s3-helm.tgz s3://${{ secrets.AWS_S3_BUCKET_NAME }}       

