name: Upload Website

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      env:
          aws_s3_bucket: ${{ secrets.AWS_S3_BUCKET }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'   # optional: defaults to us-east-1
    - name: Deploy static site to S3 bucket
      run: |
          tar -cvzf ./assessment/s3-helm.tgz ./assessment/s3-helm/
          aws s3 sync ./assessment/s3-helm.tgz s3://aws_s3_bucket/charts/                                               
